<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $cities = [
            // ===== Johor (state_id = 1) =====
            ['state_id' => 1, 'name' => 'Johor Bahru', 'postcode' => '80000'],
            ['state_id' => 1, 'name' => 'Skudai', 'postcode' => '81300'],
            ['state_id' => 1, 'name' => 'Pasir Gudang', 'postcode' => '81700'],
            ['state_id' => 1, 'name' => 'Kulai', 'postcode' => '81000'],
            ['state_id' => 1, 'name' => 'Kluang', 'postcode' => '86000'],
            ['state_id' => 1, 'name' => 'Batu Pahat', 'postcode' => '83000'],
            ['state_id' => 1, 'name' => 'Muar', 'postcode' => '84000'],
            ['state_id' => 1, 'name' => 'Segamat', 'postcode' => '85000'],
            ['state_id' => 1, 'name' => 'Pontian', 'postcode' => '82000'],
            ['state_id' => 1, 'name' => 'Kota Tinggi', 'postcode' => '81900'],
            ['state_id' => 1, 'name' => 'Mersing', 'postcode' => '86800'],
            ['state_id' => 1, 'name' => 'Tangkak', 'postcode' => '84900'],
            ['state_id' => 1, 'name' => 'Simpang Renggam', 'postcode' => '86200'],
            ['state_id' => 1, 'name' => 'Yong Peng', 'postcode' => '83700'],
            ['state_id' => 1, 'name' => 'Ayer Hitam', 'postcode' => '86100'],
            ['state_id' => 1, 'name' => 'Sri Gading', 'postcode' => '83300'],
            ['state_id' => 1, 'name' => 'Labis', 'postcode' => '85300'],
            ['state_id' => 1, 'name' => 'Benut', 'postcode' => '82200'],
            ['state_id' => 1, 'name' => 'Pekan Nanas', 'postcode' => '81500'],
            ['state_id' => 1, 'name' => 'Gelang Patah', 'postcode' => '81550'],
            ['state_id' => 1, 'name' => 'Senai', 'postcode' => '81400'],
            ['state_id' => 1, 'name' => 'Masai', 'postcode' => '81750'],
            ['state_id' => 1, 'name' => 'Ulu Tiram', 'postcode' => '81800'],
            ['state_id' => 1, 'name' => 'Nusajaya', 'postcode' => '79250'],
            ['state_id' => 1, 'name' => 'Iskandar Puteri', 'postcode' => '79100'],
            ['state_id' => 1, 'name' => 'Larkin', 'postcode' => '80350'],
            ['state_id' => 1, 'name' => 'Tampoi', 'postcode' => '81200'],
            ['state_id' => 1, 'name' => 'Tebrau', 'postcode' => '81100'],
            ['state_id' => 1, 'name' => 'Permas Jaya', 'postcode' => '81750'],
            ['state_id' => 1, 'name' => 'Kangkar Pulai', 'postcode' => '81110'],
            ['state_id' => 1, 'name' => 'Chaah', 'postcode' => '85400'],
            ['state_id' => 1, 'name' => 'Jementah', 'postcode' => '85500'],
            ['state_id' => 1, 'name' => 'Parit Raja', 'postcode' => '86400'],
            ['state_id' => 1, 'name' => 'Parit Sulong', 'postcode' => '83500'],
            ['state_id' => 1, 'name' => 'Senggarang', 'postcode' => '83100'],
            ['state_id' => 1, 'name' => 'Panchor', 'postcode' => '84500'],
            ['state_id' => 1, 'name' => 'Bukit Gambir', 'postcode' => '84800'],
            ['state_id' => 1, 'name' => 'Bakri', 'postcode' => '84200'],
            ['state_id' => 1, 'name' => 'Pagoh', 'postcode' => '84600'],
            ['state_id' => 1, 'name' => 'Kukup', 'postcode' => '82300'],
            ['state_id' => 1, 'name' => 'Desaru', 'postcode' => '81930'],

            // ===== Kedah (state_id = 2) =====
            ['state_id' => 2, 'name' => 'Alor Setar', 'postcode' => '05000'],
            ['state_id' => 2, 'name' => 'Sungai Petani', 'postcode' => '08000'],
            ['state_id' => 2, 'name' => 'Kulim', 'postcode' => '09000'],
            ['state_id' => 2, 'name' => 'Langkawi', 'postcode' => '07000'],
            ['state_id' => 2, 'name' => 'Jitra', 'postcode' => '06000'],
            ['state_id' => 2, 'name' => 'Baling', 'postcode' => '09100'],
            ['state_id' => 2, 'name' => 'Kuala Kedah', 'postcode' => '06600'],
            ['state_id' => 2, 'name' => 'Pendang', 'postcode' => '06700'],
            ['state_id' => 2, 'name' => 'Yan', 'postcode' => '06800'],
            ['state_id' => 2, 'name' => 'Sik', 'postcode' => '08200'],
            ['state_id' => 2, 'name' => 'Bandar Baharu', 'postcode' => '09800'],
            ['state_id' => 2, 'name' => 'Pokok Sena', 'postcode' => '06400'],
            ['state_id' => 2, 'name' => 'Kubang Pasu', 'postcode' => '06050'],
            ['state_id' => 2, 'name' => 'Padang Serai', 'postcode' => '09400'],
            ['state_id' => 2, 'name' => 'Gurun', 'postcode' => '08300'],
            ['state_id' => 2, 'name' => 'Guar Chempedak', 'postcode' => '08400'],
            ['state_id' => 2, 'name' => 'Lunas', 'postcode' => '09600'],
            ['state_id' => 2, 'name' => 'Bedong', 'postcode' => '08100'],
            ['state_id' => 2, 'name' => 'Kupang', 'postcode' => '09200'],
            ['state_id' => 2, 'name' => 'Changlun', 'postcode' => '06010'],
            ['state_id' => 2, 'name' => 'Bukit Kayu Hitam', 'postcode' => '06050'],
            ['state_id' => 2, 'name' => 'Kuala Nerang', 'postcode' => '06300'],
            ['state_id' => 2, 'name' => 'Merbok', 'postcode' => '08400'],
            ['state_id' => 2, 'name' => 'Kepala Batas', 'postcode' => '06200'],
            ['state_id' => 2, 'name' => 'Durian Burung', 'postcode' => '06700'],
            ['state_id' => 2, 'name' => 'Karangan', 'postcode' => '09700'],

            // ===== Kelantan (state_id = 3) =====
            ['state_id' => 3, 'name' => 'Kota Bharu', 'postcode' => '15000'],
            ['state_id' => 3, 'name' => 'Pasir Mas', 'postcode' => '17000'],
            ['state_id' => 3, 'name' => 'Tumpat', 'postcode' => '16200'],
            ['state_id' => 3, 'name' => 'Tanah Merah', 'postcode' => '17500'],
            ['state_id' => 3, 'name' => 'Machang', 'postcode' => '18500'],
            ['state_id' => 3, 'name' => 'Kuala Krai', 'postcode' => '18000'],
            ['state_id' => 3, 'name' => 'Bachok', 'postcode' => '16300'],
            ['state_id' => 3, 'name' => 'Pasir Puteh', 'postcode' => '16800'],
            ['state_id' => 3, 'name' => 'Gua Musang', 'postcode' => '18300'],
            ['state_id' => 3, 'name' => 'Jeli', 'postcode' => '17600'],
            ['state_id' => 3, 'name' => 'Rantau Panjang', 'postcode' => '17200'],
            ['state_id' => 3, 'name' => 'Wakaf Bharu', 'postcode' => '15300'],
            ['state_id' => 3, 'name' => 'Pengkalan Chepa', 'postcode' => '16100'],
            ['state_id' => 3, 'name' => 'Kubang Kerian', 'postcode' => '16150'],
            ['state_id' => 3, 'name' => 'Tok Bali', 'postcode' => '16800'],
            ['state_id' => 3, 'name' => 'Salor', 'postcode' => '15100'],
            ['state_id' => 3, 'name' => 'Dabong', 'postcode' => '18200'],
            ['state_id' => 3, 'name' => 'Lojing', 'postcode' => '18200'],
            ['state_id' => 3, 'name' => 'Peringat', 'postcode' => '16400'],
            ['state_id' => 3, 'name' => 'Melor', 'postcode' => '16400'],
            ['state_id' => 3, 'name' => 'Kadok', 'postcode' => '15200'],
            ['state_id' => 3, 'name' => 'Jelawat', 'postcode' => '15050'],

            // ===== Melaka (state_id = 4) =====
            ['state_id' => 4, 'name' => 'Melaka', 'postcode' => '75000'],
            ['state_id' => 4, 'name' => 'Alor Gajah', 'postcode' => '78000'],
            ['state_id' => 4, 'name' => 'Jasin', 'postcode' => '77000'],
            ['state_id' => 4, 'name' => 'Ayer Keroh', 'postcode' => '75450'],
            ['state_id' => 4, 'name' => 'Masjid Tanah', 'postcode' => '78300'],
            ['state_id' => 4, 'name' => 'Merlimau', 'postcode' => '77300'],
            ['state_id' => 4, 'name' => 'Sungai Udang', 'postcode' => '76300'],
            ['state_id' => 4, 'name' => 'Bukit Beruang', 'postcode' => '75450'],
            ['state_id' => 4, 'name' => 'Durian Tunggal', 'postcode' => '76100'],
            ['state_id' => 4, 'name' => 'Tanjung Kling', 'postcode' => '76400'],
            ['state_id' => 4, 'name' => 'Batu Berendam', 'postcode' => '75350'],
            ['state_id' => 4, 'name' => 'Bemban', 'postcode' => '77200'],
            ['state_id' => 4, 'name' => 'Pulau Sebang', 'postcode' => '78200'],
            ['state_id' => 4, 'name' => 'Kuala Sungai Baru', 'postcode' => '78200'],
            ['state_id' => 4, 'name' => 'Umbai', 'postcode' => '75460'],
            ['state_id' => 4, 'name' => 'Klebang', 'postcode' => '75200'],
            ['state_id' => 4, 'name' => 'Ujong Pasir', 'postcode' => '75050'],
            ['state_id' => 4, 'name' => 'Tangga Batu', 'postcode' => '76100'],
            ['state_id' => 4, 'name' => 'Bukit Rambai', 'postcode' => '75250'],
            ['state_id' => 4, 'name' => 'Cheng', 'postcode' => '75250'],

            // ===== Negeri Sembilan (state_id = 5) =====
            ['state_id' => 5, 'name' => 'Seremban', 'postcode' => '70000'],
            ['state_id' => 5, 'name' => 'Port Dickson', 'postcode' => '71000'],
            ['state_id' => 5, 'name' => 'Nilai', 'postcode' => '71800'],
            ['state_id' => 5, 'name' => 'Bahau', 'postcode' => '72100'],
            ['state_id' => 5, 'name' => 'Kuala Pilah', 'postcode' => '72000'],
            ['state_id' => 5, 'name' => 'Tampin', 'postcode' => '73000'],
            ['state_id' => 5, 'name' => 'Rembau', 'postcode' => '71300'],
            ['state_id' => 5, 'name' => 'Jelebu', 'postcode' => '71600'],
            ['state_id' => 5, 'name' => 'Mantin', 'postcode' => '71700'],
            ['state_id' => 5, 'name' => 'Senawang', 'postcode' => '70450'],
            ['state_id' => 5, 'name' => 'Labu', 'postcode' => '71900'],
            ['state_id' => 5, 'name' => 'Rantau', 'postcode' => '71100'],
            ['state_id' => 5, 'name' => 'Gemencheh', 'postcode' => '73200'],
            ['state_id' => 5, 'name' => 'Gemas', 'postcode' => '73400'],
            ['state_id' => 5, 'name' => 'Jempol', 'postcode' => '72100'],
            ['state_id' => 5, 'name' => 'Lukut', 'postcode' => '71010'],
            ['state_id' => 5, 'name' => 'Simpang Pertang', 'postcode' => '72300'],
            ['state_id' => 5, 'name' => 'Seri Menanti', 'postcode' => '72500'],
            ['state_id' => 5, 'name' => 'Kuala Klawang', 'postcode' => '71600'],
            ['state_id' => 5, 'name' => 'Rompin', 'postcode' => '73500'],
            ['state_id' => 5, 'name' => 'Pedas', 'postcode' => '71400'],
            ['state_id' => 5, 'name' => 'Linggi', 'postcode' => '71150'],
            ['state_id' => 5, 'name' => 'Siliau', 'postcode' => '72200'],

            // ===== Pahang (state_id = 6) =====
            ['state_id' => 6, 'name' => 'Kuantan', 'postcode' => '25000'],
            ['state_id' => 6, 'name' => 'Temerloh', 'postcode' => '28000'],
            ['state_id' => 6, 'name' => 'Bentong', 'postcode' => '28700'],
            ['state_id' => 6, 'name' => 'Raub', 'postcode' => '27600'],
            ['state_id' => 6, 'name' => 'Pekan', 'postcode' => '26600'],
            ['state_id' => 6, 'name' => 'Jerantut', 'postcode' => '27000'],
            ['state_id' => 6, 'name' => 'Kuala Lipis', 'postcode' => '27200'],
            ['state_id' => 6, 'name' => 'Cameron Highlands', 'postcode' => '39000'],
            ['state_id' => 6, 'name' => 'Rompin', 'postcode' => '26800'],
            ['state_id' => 6, 'name' => 'Maran', 'postcode' => '26500'],
            ['state_id' => 6, 'name' => 'Bera', 'postcode' => '28200'],
            ['state_id' => 6, 'name' => 'Mentakab', 'postcode' => '28400'],
            ['state_id' => 6, 'name' => 'Bandar Tun Razak', 'postcode' => '26900'],
            ['state_id' => 6, 'name' => 'Chenor', 'postcode' => '28100'],
            ['state_id' => 6, 'name' => 'Gambang', 'postcode' => '26300'],
            ['state_id' => 6, 'name' => 'Sungai Lembing', 'postcode' => '26200'],
            ['state_id' => 6, 'name' => 'Bukit Tinggi', 'postcode' => '28750'],
            ['state_id' => 6, 'name' => 'Triang', 'postcode' => '28600'],
            ['state_id' => 6, 'name' => 'Tanah Rata', 'postcode' => '39000'],
            ['state_id' => 6, 'name' => 'Brinchang', 'postcode' => '39100'],
            ['state_id' => 6, 'name' => 'Lanchang', 'postcode' => '28500'],
            ['state_id' => 6, 'name' => 'Bandar Jengka', 'postcode' => '26400'],
            ['state_id' => 6, 'name' => 'Muadzam Shah', 'postcode' => '26700'],
            ['state_id' => 6, 'name' => 'Dong', 'postcode' => '27400'],
            ['state_id' => 6, 'name' => 'Lipis', 'postcode' => '27200'],
            ['state_id' => 6, 'name' => 'Kuala Krau', 'postcode' => '28050'],
            ['state_id' => 6, 'name' => 'Tanjung Lumpur', 'postcode' => '25200'],
            ['state_id' => 6, 'name' => 'Beserah', 'postcode' => '26100'],
            ['state_id' => 6, 'name' => 'Balok', 'postcode' => '26100'],
            ['state_id' => 6, 'name' => 'Teluk Cempedak', 'postcode' => '25050'],
            ['state_id' => 6, 'name' => 'Genting Highlands', 'postcode' => '69000'],
            ['state_id' => 6, 'name' => 'Bukit Fraser', 'postcode' => '49000'],

            // ===== Penang (state_id = 7) =====
            ['state_id' => 7, 'name' => 'George Town', 'postcode' => '10000'],
            ['state_id' => 7, 'name' => 'Butterworth', 'postcode' => '12000'],
            ['state_id' => 7, 'name' => 'Bukit Mertajam', 'postcode' => '14000'],
            ['state_id' => 7, 'name' => 'Nibong Tebal', 'postcode' => '14300'],
            ['state_id' => 7, 'name' => 'Bayan Lepas', 'postcode' => '11900'],
            ['state_id' => 7, 'name' => 'Tanjung Bungah', 'postcode' => '11200'],
            ['state_id' => 7, 'name' => 'Gelugor', 'postcode' => '11700'],
            ['state_id' => 7, 'name' => 'Air Itam', 'postcode' => '11500'],
            ['state_id' => 7, 'name' => 'Jelutong', 'postcode' => '11600'],
            ['state_id' => 7, 'name' => 'Kepala Batas', 'postcode' => '13200'],
            ['state_id' => 7, 'name' => 'Seberang Jaya', 'postcode' => '13700'],
            ['state_id' => 7, 'name' => 'Perai', 'postcode' => '13600'],
            ['state_id' => 7, 'name' => 'Balik Pulau', 'postcode' => '11000'],
            ['state_id' => 7, 'name' => 'Permatang Pauh', 'postcode' => '13500'],
            ['state_id' => 7, 'name' => 'Tasek Gelugor', 'postcode' => '13300'],
            ['state_id' => 7, 'name' => 'Simpang Ampat', 'postcode' => '14100'],
            ['state_id' => 7, 'name' => 'Sungai Jawi', 'postcode' => '14200'],
            ['state_id' => 7, 'name' => 'Batu Maung', 'postcode' => '11960'],
            ['state_id' => 7, 'name' => 'Pulau Tikus', 'postcode' => '10250'],
            ['state_id' => 7, 'name' => 'Tanjung Tokong', 'postcode' => '10470'],
            ['state_id' => 7, 'name' => 'Teluk Bahang', 'postcode' => '11050'],
            ['state_id' => 7, 'name' => 'Paya Terubong', 'postcode' => '11060'],
            ['state_id' => 7, 'name' => 'Sungai Ara', 'postcode' => '11900'],
            ['state_id' => 7, 'name' => 'Bukit Jambul', 'postcode' => '11900'],
            ['state_id' => 7, 'name' => 'Batu Ferringhi', 'postcode' => '11100'],
            ['state_id' => 7, 'name' => 'Penaga', 'postcode' => '13100'],
            ['state_id' => 7, 'name' => 'Bertam', 'postcode' => '13200'],

            // ===== Perak (state_id = 8) =====
            ['state_id' => 8, 'name' => 'Ipoh', 'postcode' => '30000'],
            ['state_id' => 8, 'name' => 'Taiping', 'postcode' => '34000'],
            ['state_id' => 8, 'name' => 'Sitiawan', 'postcode' => '32000'],
            ['state_id' => 8, 'name' => 'Teluk Intan', 'postcode' => '36000'],
            ['state_id' => 8, 'name' => 'Lumut', 'postcode' => '32200'],
            ['state_id' => 8, 'name' => 'Kuala Kangsar', 'postcode' => '33000'],
            ['state_id' => 8, 'name' => 'Kampar', 'postcode' => '31900'],
            ['state_id' => 8, 'name' => 'Seri Manjung', 'postcode' => '32040'],
            ['state_id' => 8, 'name' => 'Batu Gajah', 'postcode' => '31000'],
            ['state_id' => 8, 'name' => 'Tapah', 'postcode' => '35000'],
            ['state_id' => 8, 'name' => 'Slim River', 'postcode' => '35800'],
            ['state_id' => 8, 'name' => 'Tanjung Malim', 'postcode' => '35900'],
            ['state_id' => 8, 'name' => 'Parit Buntar', 'postcode' => '34200'],
            ['state_id' => 8, 'name' => 'Gerik', 'postcode' => '33300'],
            ['state_id' => 8, 'name' => 'Gopeng', 'postcode' => '31600'],
            ['state_id' => 8, 'name' => 'Bidor', 'postcode' => '35500'],
            ['state_id' => 8, 'name' => 'Lenggong', 'postcode' => '33400'],
            ['state_id' => 8, 'name' => 'Sungai Siput', 'postcode' => '31100'],
            ['state_id' => 8, 'name' => 'Pangkor', 'postcode' => '32300'],
            ['state_id' => 8, 'name' => 'Behrang', 'postcode' => '35950'],
            ['state_id' => 8, 'name' => 'Proton City', 'postcode' => '35900'],
            ['state_id' => 8, 'name' => 'Selama', 'postcode' => '34100'],
            ['state_id' => 8, 'name' => 'Pengkalan Hulu', 'postcode' => '33100'],
            ['state_id' => 8, 'name' => 'Hutan Melintang', 'postcode' => '36400'],
            ['state_id' => 8, 'name' => 'Bagan Datuk', 'postcode' => '36100'],
            ['state_id' => 8, 'name' => 'Tronoh', 'postcode' => '31800'],
            ['state_id' => 8, 'name' => 'Beruas', 'postcode' => '32700'],
            ['state_id' => 8, 'name' => 'Ayer Tawar', 'postcode' => '32400'],
            ['state_id' => 8, 'name' => 'Manong', 'postcode' => '33800'],
            ['state_id' => 8, 'name' => 'Bukit Merah', 'postcode' => '34400'],
            ['state_id' => 8, 'name' => 'Chenderiang', 'postcode' => '35300'],
            ['state_id' => 8, 'name' => 'Changkat Jering', 'postcode' => '34200'],
            ['state_id' => 8, 'name' => 'Padang Rengas', 'postcode' => '33700'],
            ['state_id' => 8, 'name' => 'Simpang Pulai', 'postcode' => '31300'],
            ['state_id' => 8, 'name' => 'Chemor', 'postcode' => '31200'],
            ['state_id' => 8, 'name' => 'Kanthan', 'postcode' => '31200'],
            ['state_id' => 8, 'name' => 'Jelapang', 'postcode' => '30020'],
            ['state_id' => 8, 'name' => 'Menglembu', 'postcode' => '31450'],
            ['state_id' => 8, 'name' => 'Lahat', 'postcode' => '31500'],
            ['state_id' => 8, 'name' => 'Pusing', 'postcode' => '31550'],

            // ===== Perlis (state_id = 9) =====
            ['state_id' => 9, 'name' => 'Kangar', 'postcode' => '01000'],
            ['state_id' => 9, 'name' => 'Arau', 'postcode' => '02600'],
            ['state_id' => 9, 'name' => 'Padang Besar', 'postcode' => '02100'],
            ['state_id' => 9, 'name' => 'Kuala Perlis', 'postcode' => '02000'],
            ['state_id' => 9, 'name' => 'Simpang Empat', 'postcode' => '02700'],
            ['state_id' => 9, 'name' => 'Beseri', 'postcode' => '02200'],
            ['state_id' => 9, 'name' => 'Kaki Bukit', 'postcode' => '02200'],
            ['state_id' => 9, 'name' => 'Sanglang', 'postcode' => '02400'],
            ['state_id' => 9, 'name' => 'Mata Ayer', 'postcode' => '02500'],
            ['state_id' => 9, 'name' => 'Wang Kelian', 'postcode' => '02500'],

            // ===== Sabah (state_id = 10) =====
            ['state_id' => 10, 'name' => 'Kota Kinabalu', 'postcode' => '88000'],
            ['state_id' => 10, 'name' => 'Sandakan', 'postcode' => '90000'],
            ['state_id' => 10, 'name' => 'Tawau', 'postcode' => '91000'],
            ['state_id' => 10, 'name' => 'Lahad Datu', 'postcode' => '91100'],
            ['state_id' => 10, 'name' => 'Keningau', 'postcode' => '89000'],
            ['state_id' => 10, 'name' => 'Semporna', 'postcode' => '91300'],
            ['state_id' => 10, 'name' => 'Kudat', 'postcode' => '89050'],
            ['state_id' => 10, 'name' => 'Beaufort', 'postcode' => '89800'],
            ['state_id' => 10, 'name' => 'Papar', 'postcode' => '89600'],
            ['state_id' => 10, 'name' => 'Ranau', 'postcode' => '89300'],
            ['state_id' => 10, 'name' => 'Kota Belud', 'postcode' => '89150'],
            ['state_id' => 10, 'name' => 'Tuaran', 'postcode' => '89208'],
            ['state_id' => 10, 'name' => 'Penampang', 'postcode' => '89500'],
            ['state_id' => 10, 'name' => 'Kunak', 'postcode' => '91200'],
            ['state_id' => 10, 'name' => 'Kinabatangan', 'postcode' => '90200'],
            ['state_id' => 10, 'name' => 'Tambunan', 'postcode' => '89650'],
            ['state_id' => 10, 'name' => 'Sipitang', 'postcode' => '89850'],
            ['state_id' => 10, 'name' => 'Tenom', 'postcode' => '89900'],
            ['state_id' => 10, 'name' => 'Putatan', 'postcode' => '88200'],
            ['state_id' => 10, 'name' => 'Inanam', 'postcode' => '88450'],
            ['state_id' => 10, 'name' => 'Likas', 'postcode' => '88400'],
            ['state_id' => 10, 'name' => 'Telipok', 'postcode' => '89200'],
            ['state_id' => 10, 'name' => 'Menggatal', 'postcode' => '88450'],
            ['state_id' => 10, 'name' => 'Donggongon', 'postcode' => '89500'],
            ['state_id' => 10, 'name' => 'Kota Marudu', 'postcode' => '89100'],
            ['state_id' => 10, 'name' => 'Pitas', 'postcode' => '89100'],
            ['state_id' => 10, 'name' => 'Tongod', 'postcode' => '89200'],
            ['state_id' => 10, 'name' => 'Beluran', 'postcode' => '90100'],
            ['state_id' => 10, 'name' => 'Kuala Penyu', 'postcode' => '89740'],
            ['state_id' => 10, 'name' => 'Nabawan', 'postcode' => '89950'],
            ['state_id' => 10, 'name' => 'Kalabakan', 'postcode' => '91110'],
            ['state_id' => 10, 'name' => 'Kimanis', 'postcode' => '89740'],

            // ===== Sarawak (state_id = 11) =====
            ['state_id' => 11, 'name' => 'Kuching', 'postcode' => '93000'],
            ['state_id' => 11, 'name' => 'Miri', 'postcode' => '98000'],
            ['state_id' => 11, 'name' => 'Sibu', 'postcode' => '96000'],
            ['state_id' => 11, 'name' => 'Bintulu', 'postcode' => '97000'],
            ['state_id' => 11, 'name' => 'Limbang', 'postcode' => '98700'],
            ['state_id' => 11, 'name' => 'Sarikei', 'postcode' => '96100'],
            ['state_id' => 11, 'name' => 'Sri Aman', 'postcode' => '95000'],
            ['state_id' => 11, 'name' => 'Kapit', 'postcode' => '96800'],
            ['state_id' => 11, 'name' => 'Mukah', 'postcode' => '96400'],
            ['state_id' => 11, 'name' => 'Lawas', 'postcode' => '98800'],
            ['state_id' => 11, 'name' => 'Lundu', 'postcode' => '94500'],
            ['state_id' => 11, 'name' => 'Betong', 'postcode' => '95500'],
            ['state_id' => 11, 'name' => 'Serian', 'postcode' => '94700'],
            ['state_id' => 11, 'name' => 'Saratok', 'postcode' => '95400'],
            ['state_id' => 11, 'name' => 'Marudi', 'postcode' => '98050'],
            ['state_id' => 11, 'name' => 'Dalat', 'postcode' => '96300'],
            ['state_id' => 11, 'name' => 'Tatau', 'postcode' => '97100'],
            ['state_id' => 11, 'name' => 'Belaga', 'postcode' => '96900'],
            ['state_id' => 11, 'name' => 'Bau', 'postcode' => '94000'],
            ['state_id' => 11, 'name' => 'Simunjan', 'postcode' => '94800'],
            ['state_id' => 11, 'name' => 'Kota Samarahan', 'postcode' => '94300'],
            ['state_id' => 11, 'name' => 'Asajaya', 'postcode' => '94600'],
            ['state_id' => 11, 'name' => 'Samarahan', 'postcode' => '94300'],
            ['state_id' => 11, 'name' => 'Kanowit', 'postcode' => '96700'],
            ['state_id' => 11, 'name' => 'Julau', 'postcode' => '96600'],
            ['state_id' => 11, 'name' => 'Song', 'postcode' => '96850'],
            ['state_id' => 11, 'name' => 'Daro', 'postcode' => '96200'],
            ['state_id' => 11, 'name' => 'Maradong', 'postcode' => '96500'],
            ['state_id' => 11, 'name' => 'Selangau', 'postcode' => '96500'],
            ['state_id' => 11, 'name' => 'Beluru', 'postcode' => '98050'],
            ['state_id' => 11, 'name' => 'Pusa', 'postcode' => '95300'],
            ['state_id' => 11, 'name' => 'Tebedu', 'postcode' => '94800'],
            ['state_id' => 11, 'name' => 'Lubok Antu', 'postcode' => '95900'],
            ['state_id' => 11, 'name' => 'Nanga Medamit', 'postcode' => '98700'],

            // ===== Selangor (state_id = 12) =====
            ['state_id' => 12, 'name' => 'Shah Alam', 'postcode' => '40000'],
            ['state_id' => 12, 'name' => 'Petaling Jaya', 'postcode' => '46000'],
            ['state_id' => 12, 'name' => 'Subang Jaya', 'postcode' => '47500'],
            ['state_id' => 12, 'name' => 'Klang', 'postcode' => '41000'],
            ['state_id' => 12, 'name' => 'Ampang', 'postcode' => '68000'],
            ['state_id' => 12, 'name' => 'Rawang', 'postcode' => '48000'],
            ['state_id' => 12, 'name' => 'Kajang', 'postcode' => '43000'],
            ['state_id' => 12, 'name' => 'Bangi', 'postcode' => '43600'],
            ['state_id' => 12, 'name' => 'Puchong', 'postcode' => '47100'],
            ['state_id' => 12, 'name' => 'Serdang', 'postcode' => '43300'],
            ['state_id' => 12, 'name' => 'Sepang', 'postcode' => '43900'],
            ['state_id' => 12, 'name' => 'Cyberjaya', 'postcode' => '63000'],
            ['state_id' => 12, 'name' => 'Selayang', 'postcode' => '68100'],
            ['state_id' => 12, 'name' => 'Batu Caves', 'postcode' => '68100'],
            ['state_id' => 12, 'name' => 'Gombak', 'postcode' => '68100'],
            ['state_id' => 12, 'name' => 'Hulu Langat', 'postcode' => '43100'],
            ['state_id' => 12, 'name' => 'Kuala Selangor', 'postcode' => '45000'],
            ['state_id' => 12, 'name' => 'Sabak Bernam', 'postcode' => '45200'],
            ['state_id' => 12, 'name' => 'Tanjung Karang', 'postcode' => '45500'],
            ['state_id' => 12, 'name' => 'Kuala Kubu Bharu', 'postcode' => '44000'],
            ['state_id' => 12, 'name' => 'Semenyih', 'postcode' => '43500'],
            ['state_id' => 12, 'name' => 'Beranang', 'postcode' => '43700'],
            ['state_id' => 12, 'name' => 'Dengkil', 'postcode' => '43800'],
            ['state_id' => 12, 'name' => 'Banting', 'postcode' => '42700'],
            ['state_id' => 12, 'name' => 'Jenjarom', 'postcode' => '42600'],
            ['state_id' => 12, 'name' => 'Telok Panglima Garang', 'postcode' => '42500'],
            ['state_id' => 12, 'name' => 'Sungai Buloh', 'postcode' => '47000'],
            ['state_id' => 12, 'name' => 'Damansara', 'postcode' => '47800'],
            ['state_id' => 12, 'name' => 'Kelana Jaya', 'postcode' => '47301'],
            ['state_id' => 12, 'name' => 'USJ', 'postcode' => '47600'],
            ['state_id' => 12, 'name' => 'Bukit Jelutong', 'postcode' => '40150'],
            ['state_id' => 12, 'name' => 'Setia Alam', 'postcode' => '40170'],
            ['state_id' => 12, 'name' => 'Kota Damansara', 'postcode' => '47810'],
            ['state_id' => 12, 'name' => 'Ara Damansara', 'postcode' => '47301'],
            ['state_id' => 12, 'name' => 'Bandar Sunway', 'postcode' => '47500'],
            ['state_id' => 12, 'name' => 'Bukit Raja', 'postcode' => '41050'],
            ['state_id' => 12, 'name' => 'Port Klang', 'postcode' => '42000'],
            ['state_id' => 12, 'name' => 'Pelabuhan Klang', 'postcode' => '42005'],
            ['state_id' => 12, 'name' => 'Pandamaran', 'postcode' => '42000'],
            ['state_id' => 12, 'name' => 'Kapar', 'postcode' => '42100'],
            ['state_id' => 12, 'name' => 'Meru', 'postcode' => '41050'],
            ['state_id' => 12, 'name' => 'Batang Kali', 'postcode' => '44300'],
            ['state_id' => 12, 'name' => 'Kerling', 'postcode' => '44100'],
            ['state_id' => 12, 'name' => 'Sekinchan', 'postcode' => '45400'],
            ['state_id' => 12, 'name' => 'Sungai Besar', 'postcode' => '45300'],
            ['state_id' => 12, 'name' => 'Bestari Jaya', 'postcode' => '45600'],
            ['state_id' => 12, 'name' => 'Ijok', 'postcode' => '45620'],
            ['state_id' => 12, 'name' => 'Bukit Beruntung', 'postcode' => '48300'],
            ['state_id' => 12, 'name' => 'Serendah', 'postcode' => '48200'],
            ['state_id' => 12, 'name' => 'Cheras', 'postcode' => '43200'],
            ['state_id' => 12, 'name' => 'Balakong', 'postcode' => '43300'],
            ['state_id' => 12, 'name' => 'Seri Kembangan', 'postcode' => '43300'],
            ['state_id' => 12, 'name' => 'Salak Tinggi', 'postcode' => '43900'],
            ['state_id' => 12, 'name' => 'KLIA', 'postcode' => '64000'],

            // ===== Terengganu (state_id = 13) =====
            ['state_id' => 13, 'name' => 'Kuala Terengganu', 'postcode' => '20000'],
            ['state_id' => 13, 'name' => 'Kemaman', 'postcode' => '24000'],
            ['state_id' => 13, 'name' => 'Dungun', 'postcode' => '23000'],
            ['state_id' => 13, 'name' => 'Marang', 'postcode' => '21600'],
            ['state_id' => 13, 'name' => 'Hulu Terengganu', 'postcode' => '21700'],
            ['state_id' => 13, 'name' => 'Besut', 'postcode' => '22300'],
            ['state_id' => 13, 'name' => 'Setiu', 'postcode' => '22100'],
            ['state_id' => 13, 'name' => 'Chukai', 'postcode' => '24000'],
            ['state_id' => 13, 'name' => 'Kerteh', 'postcode' => '24300'],
            ['state_id' => 13, 'name' => 'Paka', 'postcode' => '23100'],
            ['state_id' => 13, 'name' => 'Kuala Besut', 'postcode' => '22300'],
            ['state_id' => 13, 'name' => 'Jerteh', 'postcode' => '22000'],
            ['state_id' => 13, 'name' => 'Permaisuri', 'postcode' => '22100'],
            ['state_id' => 13, 'name' => 'Ajil', 'postcode' => '21800'],
            ['state_id' => 13, 'name' => 'Kuala Berang', 'postcode' => '21700'],
            ['state_id' => 13, 'name' => 'Bukit Payong', 'postcode' => '21400'],
            ['state_id' => 13, 'name' => 'Chendering', 'postcode' => '21080'],
            ['state_id' => 13, 'name' => 'Tok Jembal', 'postcode' => '21300'],
            ['state_id' => 13, 'name' => 'Batu Rakit', 'postcode' => '21020'],
            ['state_id' => 13, 'name' => 'Kampung Raja', 'postcode' => '22500'],
            ['state_id' => 13, 'name' => 'Kemasik', 'postcode' => '24200'],
            ['state_id' => 13, 'name' => 'Merchang', 'postcode' => '23050'],
            ['state_id' => 13, 'name' => 'Sura', 'postcode' => '23000'],

            // ===== Kuala Lumpur (state_id = 14) =====
            ['state_id' => 14, 'name' => 'Kuala Lumpur', 'postcode' => '50000'],
            ['state_id' => 14, 'name' => 'Cheras', 'postcode' => '56000'],
            ['state_id' => 14, 'name' => 'Wangsa Maju', 'postcode' => '53300'],
            ['state_id' => 14, 'name' => 'Setapak', 'postcode' => '53000'],
            ['state_id' => 14, 'name' => 'Kepong', 'postcode' => '52000'],
            ['state_id' => 14, 'name' => 'Segambut', 'postcode' => '51200'],
            ['state_id' => 14, 'name' => 'Sentul', 'postcode' => '51000'],
            ['state_id' => 14, 'name' => 'Titiwangsa', 'postcode' => '50400'],
            ['state_id' => 14, 'name' => 'Bukit Bintang', 'postcode' => '55100'],
            ['state_id' => 14, 'name' => 'Lembah Pantai', 'postcode' => '59200'],
            ['state_id' => 14, 'name' => 'Bandar Tun Razak', 'postcode' => '56000'],
            ['state_id' => 14, 'name' => 'Setiawangsa', 'postcode' => '54200'],
            ['state_id' => 14, 'name' => 'Batu', 'postcode' => '51100'],
            ['state_id' => 14, 'name' => 'Sri Petaling', 'postcode' => '57000'],
            ['state_id' => 14, 'name' => 'Bukit Jalil', 'postcode' => '57000'],
            ['state_id' => 14, 'name' => 'Bangsar', 'postcode' => '59000'],
            ['state_id' => 14, 'name' => 'Mont Kiara', 'postcode' => '50480'],
            ['state_id' => 14, 'name' => 'Desa Petaling', 'postcode' => '57100'],
            ['state_id' => 14, 'name' => 'Taman Tun Dr Ismail', 'postcode' => '60000'],
            ['state_id' => 14, 'name' => 'Pantai Dalam', 'postcode' => '59200'],
            ['state_id' => 14, 'name' => 'Jalan Klang Lama', 'postcode' => '58000'],
            ['state_id' => 14, 'name' => 'Sungai Besi', 'postcode' => '57100'],
            ['state_id' => 14, 'name' => 'Salak Selatan', 'postcode' => '57100'],
            ['state_id' => 14, 'name' => 'Seputeh', 'postcode' => '58000'],
            ['state_id' => 14, 'name' => 'Bandar Tasik Selatan', 'postcode' => '57000'],
            ['state_id' => 14, 'name' => 'Taman Desa', 'postcode' => '58100'],
            ['state_id' => 14, 'name' => 'Damansara Heights', 'postcode' => '50490'],
            ['state_id' => 14, 'name' => 'Kampung Baru', 'postcode' => '50300'],
            ['state_id' => 14, 'name' => 'Jalan Sultan Ismail', 'postcode' => '50250'],
            ['state_id' => 14, 'name' => 'KLCC', 'postcode' => '50088'],
            ['state_id' => 14, 'name' => 'KL Sentral', 'postcode' => '50470'],
            ['state_id' => 14, 'name' => 'Mid Valley', 'postcode' => '59200'],
            ['state_id' => 14, 'name' => 'Hartamas', 'postcode' => '50480'],

            // ===== Additional Johor =====
            ['state_id' => 1, 'name' => 'Taman Molek', 'postcode' => '81100'],
            ['state_id' => 1, 'name' => 'Bandar Tenggara', 'postcode' => '81440'],
            ['state_id' => 1, 'name' => 'Rengit', 'postcode' => '83100'],
            ['state_id' => 1, 'name' => 'Kelapa Sawit', 'postcode' => '81170'],
            ['state_id' => 1, 'name' => 'Paloh', 'postcode' => '86600'],
            ['state_id' => 1, 'name' => 'Endau', 'postcode' => '86900'],

            // ===== Additional Kedah =====
            ['state_id' => 2, 'name' => 'Padang Matsirat', 'postcode' => '07100'],
            ['state_id' => 2, 'name' => 'Kuah', 'postcode' => '07000'],
            ['state_id' => 2, 'name' => 'Tanjung Dawai', 'postcode' => '08000'],
            ['state_id' => 2, 'name' => 'Jeniang', 'postcode' => '08300'],

            // ===== Additional Kelantan =====
            ['state_id' => 3, 'name' => 'Ketereh', 'postcode' => '16450'],
            ['state_id' => 3, 'name' => 'Cherang Ruku', 'postcode' => '16700'],
            ['state_id' => 3, 'name' => 'Selising', 'postcode' => '16810'],

            // ===== Additional Pahang =====
            ['state_id' => 6, 'name' => 'Kuala Rompin', 'postcode' => '26800'],
            ['state_id' => 6, 'name' => 'Sungai Koyan', 'postcode' => '27650'],
            ['state_id' => 6, 'name' => 'Ringlet', 'postcode' => '39200'],
            ['state_id' => 6, 'name' => 'Kuala Tahan', 'postcode' => '27000'],

            // ===== Additional Penang =====
            ['state_id' => 7, 'name' => 'Dato Keramat', 'postcode' => '10150'],
            ['state_id' => 7, 'name' => 'Tanjung Bunga', 'postcode' => '11200'],
            ['state_id' => 7, 'name' => 'Sungai Dua', 'postcode' => '11700'],
            ['state_id' => 7, 'name' => 'Minden Heights', 'postcode' => '11700'],

            // ===== Additional Perak =====
            ['state_id' => 8, 'name' => 'Kuala Sepetang', 'postcode' => '34650'],
            ['state_id' => 8, 'name' => 'Trong', 'postcode' => '34800'],
            ['state_id' => 8, 'name' => 'Sungai Perak', 'postcode' => '36020'],
            ['state_id' => 8, 'name' => 'Langkap', 'postcode' => '36500'],
            ['state_id' => 8, 'name' => 'Bagan Serai', 'postcode' => '34300'],
            ['state_id' => 8, 'name' => 'Kuala Kurau', 'postcode' => '34350'],

            // ===== Additional Sabah =====
            ['state_id' => 10, 'name' => 'Kundasang', 'postcode' => '89300'],
            ['state_id' => 10, 'name' => 'Tamparuli', 'postcode' => '89250'],
            ['state_id' => 10, 'name' => 'Membakut', 'postcode' => '89720'],
            ['state_id' => 10, 'name' => 'Kuamut', 'postcode' => '91200'],

            // ===== Additional Sarawak =====
            ['state_id' => 11, 'name' => 'Petra Jaya', 'postcode' => '93050'],
            ['state_id' => 11, 'name' => 'Padawan', 'postcode' => '93250'],
            ['state_id' => 11, 'name' => 'Bako', 'postcode' => '93050'],
            ['state_id' => 11, 'name' => 'Senadin', 'postcode' => '98000'],
            ['state_id' => 11, 'name' => 'Lutong', 'postcode' => '98100'],
            ['state_id' => 11, 'name' => 'Niah', 'postcode' => '98200'],
            ['state_id' => 11, 'name' => 'Subis', 'postcode' => '98150'],

            // ===== Additional Selangor =====
            ['state_id' => 12, 'name' => 'Hulu Selangor', 'postcode' => '44000'],
            ['state_id' => 12, 'name' => 'Kuang', 'postcode' => '48050'],
            ['state_id' => 12, 'name' => 'Taman Melawati', 'postcode' => '53100'],
            ['state_id' => 12, 'name' => 'Pandan Indah', 'postcode' => '55100'],
            ['state_id' => 12, 'name' => 'Bukit Mahkota', 'postcode' => '43000'],
            ['state_id' => 12, 'name' => 'Sungai Pelek', 'postcode' => '43950'],
            ['state_id' => 12, 'name' => 'Taman Equine', 'postcode' => '43300'],
            ['state_id' => 12, 'name' => 'Kota Kemuning', 'postcode' => '40460'],

            // ===== Additional Terengganu =====
            ['state_id' => 13, 'name' => 'Bandar Al-Muktafi Billah Shah', 'postcode' => '23400'],
            ['state_id' => 13, 'name' => 'Rantau Abang', 'postcode' => '23050'],
            ['state_id' => 13, 'name' => 'Kuala Nerus', 'postcode' => '21060'],

            // ===== Additional KL =====
            ['state_id' => 14, 'name' => 'Taman Melati', 'postcode' => '53100'],
            ['state_id' => 14, 'name' => 'Danau Kota', 'postcode' => '53300'],
            ['state_id' => 14, 'name' => 'Taman Permata', 'postcode' => '53300'],
            ['state_id' => 14, 'name' => 'Jinjang', 'postcode' => '52000'],
            ['state_id' => 14, 'name' => 'Taman Connaught', 'postcode' => '56000'],
            ['state_id' => 14, 'name' => 'Taman Midah', 'postcode' => '56000'],
            ['state_id' => 14, 'name' => 'Taman Maluri', 'postcode' => '55100'],

            // ===== Additional Negeri Sembilan =====
            ['state_id' => 5, 'name' => 'Ampangan', 'postcode' => '70400'],
            ['state_id' => 5, 'name' => 'Lenggeng', 'postcode' => '71750'],
            ['state_id' => 5, 'name' => 'Titi', 'postcode' => '71500'],

            // ===== Additional Melaka =====
            ['state_id' => 4, 'name' => 'Batang Melaka', 'postcode' => '78000'],
            ['state_id' => 4, 'name' => 'Gadek', 'postcode' => '78100'],
            ['state_id' => 4, 'name' => 'Simpang Ampat', 'postcode' => '78100'],
            ['state_id' => 4, 'name' => 'Tanjung Bidara', 'postcode' => '78300'],
            ['state_id' => 4, 'name' => 'Selandar', 'postcode' => '77500'],

            // ===== Additional Perlis =====
            ['state_id' => 9, 'name' => 'Chuping', 'postcode' => '02500'],

            // ===== Additional Johor =====
            ['state_id' => 1, 'name' => 'Sri Medan', 'postcode' => '83400'],
            ['state_id' => 1, 'name' => 'Buloh Kasap', 'postcode' => '85100'],
            ['state_id' => 1, 'name' => 'Semerah', 'postcode' => '83600'],

            // ===== Additional Sabah =====
            ['state_id' => 10, 'name' => 'Telupid', 'postcode' => '89200'],

            // ===== Additional Perak =====
            ['state_id' => 8, 'name' => 'Seri Iskandar', 'postcode' => '32610'],
            ['state_id' => 8, 'name' => 'Malim Nawar', 'postcode' => '31700'],

            // ===== Additional Selangor =====
            ['state_id' => 12, 'name' => 'Tanjung Sepat', 'postcode' => '42800'],
            ['state_id' => 12, 'name' => 'Morib', 'postcode' => '42700'],

            // ===== Additional Sarawak =====
            ['state_id' => 11, 'name' => 'Engkilili', 'postcode' => '95800'],

            // ===== Labuan (state_id = 15) =====
            ['state_id' => 15, 'name' => 'Labuan', 'postcode' => '87000'],
            ['state_id' => 15, 'name' => 'Victoria', 'postcode' => '87007'],
            ['state_id' => 15, 'name' => 'Rancha-Rancha', 'postcode' => '87000'],
            ['state_id' => 15, 'name' => 'Kiamsam', 'postcode' => '87010'],
            ['state_id' => 15, 'name' => 'Layang-Layangan', 'postcode' => '87020'],
            ['state_id' => 15, 'name' => 'Pohon Batu', 'postcode' => '87000'],

            // ===== Putrajaya (state_id = 16) =====
            ['state_id' => 16, 'name' => 'Putrajaya', 'postcode' => '62000'],
            ['state_id' => 16, 'name' => 'Presint 1', 'postcode' => '62000'],
            ['state_id' => 16, 'name' => 'Presint 2', 'postcode' => '62100'],
            ['state_id' => 16, 'name' => 'Presint 3', 'postcode' => '62300'],
            ['state_id' => 16, 'name' => 'Presint 4', 'postcode' => '62504'],
            ['state_id' => 16, 'name' => 'Presint 5', 'postcode' => '62200'],
            ['state_id' => 16, 'name' => 'Presint 8', 'postcode' => '62250'],
            ['state_id' => 16, 'name' => 'Presint 9', 'postcode' => '62250'],
            ['state_id' => 16, 'name' => 'Presint 11', 'postcode' => '62300'],
            ['state_id' => 16, 'name' => 'Presint 14', 'postcode' => '62050'],
            ['state_id' => 16, 'name' => 'Presint 15', 'postcode' => '62050'],
            ['state_id' => 16, 'name' => 'Presint 16', 'postcode' => '62150'],
            ['state_id' => 16, 'name' => 'Presint 17', 'postcode' => '62100'],
            ['state_id' => 16, 'name' => 'Presint 18', 'postcode' => '62602'],
        ];

        // Add timestamps and bulk insert in chunks
        $cities = array_map(function ($city) use ($now) {
            $city['created_at'] = $now;
            $city['updated_at'] = $now;
            return $city;
        }, $cities);

        foreach (array_chunk($cities, 100) as $chunk) {
            DB::table('cities')->insert($chunk);
        }
    }
}
