<!DOCTYPE html>
<html>
<head>
    <title>Stock Return - {{ $stockReturn->issue_no }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 5px; }
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .items-table th, .items-table td { border: 1px solid #000; padding: 8px; text-align: left; }
        .items-table th { background-color: #f0f0f0; }
        .signature { margin-top: 50px; }
        .signature-line { border-top: 1px solid #000; width: 200px; display: inline-block; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px;">Print</button>
        <button onclick="window.close()" style="padding: 10px 20px;">Close</button>
    </div>

    <div class="header">
        <h2>STOCK RETURN</h2>
        <p>{{ $stockReturn->issue_no }}</p>
    </div>

    <table class="info-table">
        <tr>
            <td width="15%"><strong>Return Date:</strong></td>
            <td width="35%">{{ $stockReturn->issue_date->format('d M Y') }}</td>
            <td width="15%"><strong>Status:</strong></td>
            <td width="35%">{{ strtoupper($stockReturn->status) }}</td>
        </tr>
        <tr>
            <td><strong>From Technician:</strong></td>
            <td>{{ $stockReturn->fromTechnician->name }}</td>
            <td><strong>To Depot:</strong></td>
            <td>{{ $stockReturn->toDepot->depot_name }}</td>
        </tr>
        @if($stockReturn->remarks)
        <tr>
            <td><strong>Remarks:</strong></td>
            <td colspan="3">{{ $stockReturn->remarks }}</td>
        </tr>
        @endif
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th width="5%">#</th>
                <th width="30%">Model</th>
                <th width="25%">Serial No</th>
                <th width="10%">Qty</th>
                <th width="15%">Condition</th>
                <th width="15%">Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($stockReturn->lines as $line)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $line->model->model_name }}</td>
                <td>{{ $line->serial_no ?? '-' }}</td>
                <td>{{ $line->quantity }}</td>
                <td>{{ strtoupper($line->condition) }}</td>
                <td>{{ $line->remarks ?? '-' }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3" style="text-align: right;">Total:</th>
                <th>{{ $stockReturn->total_items }}</th>
                <th colspan="2"></th>
            </tr>
        </tfoot>
    </table>

    <div class="signature">
        <table width="100%">
            <tr>
                <td width="50%">
                    <p>Returned By (Technician):</p>
                    <br><br>
                    <div class="signature-line"></div>
                    <p>{{ $stockReturn->fromTechnician->name }}</p>
                    <p>Date: _________________</p>
                </td>
                <td width="50%">
                    <p>Received By (Depot):</p>
                    <br><br>
                    <div class="signature-line"></div>
                    <p>Name: _________________</p>
                    <p>Date: _________________</p>
                </td>
            </tr>
        </table>
    </div>

    <div style="margin-top: 30px; text-align: center; font-size: 10px; color: #666;">
        <p>Printed on: {{ now()->format('d M Y H:i:s') }} | Generated by TMS</p>
    </div>
</body>
</html>
